stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
  script: 
   - echo "Start test"
  tags:
   - netology

build:
  stage: build
  image: docker:latest
  script:
   - docker build 
  tags:
   - netology
