stages:
  - test
  - build

test:
  stage: test
  image: nginx:latest
  script: 
   - go test .
  tags:
   - netology

build:
  stage: build
  image: docker:latest
  script:
   - docker build 
  tags:
   - netology
