stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script:
   - echo "Start test"
   - go test .
  tags:
   - netology


build:
  stage: build
  image: docker:latest
  script:
   - echo "Start build"
   - docker build .
  tags:
   - netology
